spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sv.svsoft.fun:7848/SV?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: sv
    password: sv@8004
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8848
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
#logging:
#  config: classpath:log4j2.xml